/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AdvertiserRole;

import Business.Advertising.TagParameterConfigs;
import Business.Organization.AdvertiserOrganization;
import Business.Publisher.Tag;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.HTML;

/**
 *
 * @author anirudhbedre
 */

public class ConfigureDSPJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConfigureDSPJPanel
     */
    private JPanel userProcessContainer;
    private AdvertiserOrganization organization;
    public ConfigureDSPJPanel(JPanel userProcessContainer, AdvertiserOrganization organization){  
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organization=organization;
        populateTagTable();
    }

    private void populateTagTable(){
        DefaultTableModel model = (DefaultTableModel) tagsJTable.getModel();
        
        model.setRowCount(0);
        
        for (TagParameterConfigs tagParameterConfigs : organization.getDsp().getTagParameterConfigsList().getTagParameterConfigsList()){
            Object[] row = new Object[1];
            row[0] = tagParameterConfigs;
         
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tagsJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tagNameJTextField = new javax.swing.JTextField();
        numberOfVisitsJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        selectTagButton = new javax.swing.JButton();
        setJButton = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Configure DSP");

        tagsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tag Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tagsJTable);

        jLabel2.setText("Tag Name");

        tagNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tagNameJTextField.setEnabled(false);

        jLabel3.setText("Number Of Visits: ");

        jLabel4.setText("% Percentage of Base Bidding Amount");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Vary Bidding Amount depending on parameters:");

        selectTagButton.setText("Select Tag");
        selectTagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTagButtonActionPerformed(evt);
            }
        });

        setJButton.setText("Set");
        setJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setJButtonActionPerformed(evt);
            }
        });

        backJButton1.setText("<< Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tagNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(setJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backJButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(416, 416, 416)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(selectTagButton)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(533, 533, 533)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberOfVisitsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectTagButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tagNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfVisitsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setJButton)
                .addGap(18, 18, 18)
                .addComponent(backJButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectTagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTagButtonActionPerformed
        // TODO add your handling code here:
          int selectedRow = tagsJTable.getSelectedRow();
        if(selectedRow>=0)
        {
            TagParameterConfigs tagParameterConfigs = (TagParameterConfigs)tagsJTable.getValueAt(selectedRow, 0);
            tagNameJTextField.setText(tagParameterConfigs.getTagName());
            numberOfVisitsJTextField.setText(String.valueOf(tagParameterConfigs.getPriceOnNumberOfVisits()));
           
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a row to view!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_selectTagButtonActionPerformed

    private void setJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setJButtonActionPerformed
        // TODO add your handling code here:
        if(tagNameJTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please select a tag !", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try{
        int priceOnNumberofVisits=Integer.parseInt(numberOfVisitsJTextField.getText());
        
        organization.getDsp().getTagParameterConfigsList().createOrUpdateTagParameterConfigs(tagNameJTextField.getText(), priceOnNumberofVisits);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a valid number!", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_setJButtonActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numberOfVisitsJTextField;
    private javax.swing.JButton selectTagButton;
    private javax.swing.JButton setJButton;
    private javax.swing.JTextField tagNameJTextField;
    private javax.swing.JTable tagsJTable;
    // End of variables declaration//GEN-END:variables
}
