/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AdvertiserRole;

import Business.Advertising.Ad;
import Business.Advertising.DSP;
import Business.Organization.AdvertiserOrganization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anirudhbedre
 */
public class ManageAdsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAdsJPanel
     */
    private JPanel userProcessContainer;
    private AdvertiserOrganization organization;
    public ManageAdsJPanel(JPanel userProcessContainer,AdvertiserOrganization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organization=organization;
        
        populateAdsCombo();
    }
    

    private void populateAdsCombo(){
        adComboBox.removeAllItems();
        
            adComboBox.addItem("Spotify");
            adComboBox.addItem("Nike");
            adComboBox.addItem("Kindle");
            adComboBox.addItem("Netflix");
            adComboBox.addItem("Xfinity");
            adComboBox.addItem("Apple Ipod");
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectAdJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        adComboBox = new javax.swing.JComboBox();
        adJLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Manage Ads");

        selectAdJButton.setText("Select Ad");
        selectAdJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAdJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Ad :");

        adComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        adComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adComboBoxActionPerformed(evt);
            }
        });

        adJLabel.setText("Ad");

        jLabel5.setText("Ad Preview:");

        backJButton1.setText("<< Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                            .addComponent(adComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(backJButton1)
                        .addGap(41, 41, 41)
                        .addComponent(selectAdJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAdJButton)
                    .addComponent(backJButton1))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectAdJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAdJButtonActionPerformed
        // TODO add your handling code here:
        String image="NoAd";
        if(adComboBox.getSelectedItem().equals("Spotify"))
            image="/UserInterface/ConsumerRole/spotify_ad.jpg";
        else if (adComboBox.getSelectedItem().equals("Nike"))
            image="/UserInterface/ConsumerRole/nike_ad.jpg";
         else if (adComboBox.getSelectedItem().equals("Apple Ipod"))
            image="/UserInterface/ConsumerRole/ipod_ad.jpg";
        else if (adComboBox.getSelectedItem().equals("Kindle"))
            image="/UserInterface/ConsumerRole/kindle_ad.png";
        else if (adComboBox.getSelectedItem().equals("Netflix"))
            image="/UserInterface/ConsumerRole/netflix_ad.png";    
        else if (adComboBox.getSelectedItem().equals("Xfinity"))
            image="/UserInterface/ConsumerRole/xfinity_ad.jpg";    
        else
             image="/UserInterface/ConsumerRole/no_ad.png";
        JOptionPane.showMessageDialog(null, "Ad image selected :"+image, "Warning", JOptionPane.WARNING_MESSAGE);
        
        Ad ad=organization.getAd();
        ad.setAdImage(image);
        adJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));
       
        
        
    }//GEN-LAST:event_selectAdJButtonActionPerformed

    private void adComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adComboBoxActionPerformed
        // TODO add your handling code here:

         
    }//GEN-LAST:event_adComboBoxActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
       ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox adComboBox;
    private javax.swing.JLabel adJLabel;
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton selectAdJButton;
    // End of variables declaration//GEN-END:variables
}
