/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AdExchangeRole;

import Business.AdExchange.AuctionEvent;
import Business.AdExchange.AuctionEventDirectory;
import Business.AdExchange.Bid;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anirudhbedre
 */
public class ViewAuctionEventDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAuctionEventDetailsJPanel
     */
    private JPanel userProcessContainer;
    private AuctionEvent auctionEvent;
    public ViewAuctionEventDetailsJPanel(JPanel userProcessContainer,AuctionEvent auctionEvent) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.auctionEvent=auctionEvent;
        
        auctionIDJLabel.setText(String.valueOf(auctionEvent.getAuctionID()));
        winnerIDJTextField.setText(String.valueOf(auctionEvent.getWinnerOfAuction()));
        winningBidAmountJTextField.setText(String.valueOf(auctionEvent.getWinningBidAmount()));
        populateAuctionEventDetailsTable();
    }

    private void populateAuctionEventDetailsTable(){
          int rowCount = auctionEventDetailsJTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)auctionEventDetailsJTable.getModel();
        model.setRowCount(0);
      
        
        
        for(Bid bid:auctionEvent.getBidList()) {
          
            Object row[] = new Object[2];
            row[0] = bid;
            row[1] = bid.getBidAmount();
            model.addRow(row);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        auctionIDJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        auctionEventDetailsJTable = new javax.swing.JTable();
        backjButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        winningBidAmountJTextField = new javax.swing.JTextField();
        winnerIDJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        auctionIDJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        auctionIDJLabel.setText("AuctionID");

        auctionEventDetailsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Advertiser ID", "Bid Amount ($)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(auctionEventDetailsJTable);

        backjButton2.setText("<<Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Winning bid amount:    $");

        jLabel2.setText("ID of winner:");

        winningBidAmountJTextField.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        winnerIDJTextField.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Auction ID: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backjButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(winningBidAmountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(winnerIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(auctionIDJLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auctionIDJLabel)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(winningBidAmountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(winnerIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backjButton2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable auctionEventDetailsJTable;
    private javax.swing.JLabel auctionIDJLabel;
    private javax.swing.JButton backjButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField winnerIDJTextField;
    private javax.swing.JTextField winningBidAmountJTextField;
    // End of variables declaration//GEN-END:variables
}
