/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PublisherRole;

import Business.Ecosystem;
import Business.Organization.PublisherOrganization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author anirudhbedre
 */
public class PublisherWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PublisherWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Ecosystem business;
    private PublisherOrganization organization;
    public PublisherWorkAreaJPanel(JPanel upc, Ecosystem business,PublisherOrganization organization) {
        initComponents();
        this.userProcessContainer=upc;
        this.business=business;
        this.organization=organization;
        accountBalanceJTextField.setText(String.valueOf(organization.getAccount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        accountBalanceJTextField = new javax.swing.JTextField();
        viewUserPotentialJButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Publisher Work Area ");

        jLabel3.setText("Account Balance:     $");

        accountBalanceJTextField.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        accountBalanceJTextField.setEnabled(false);
        accountBalanceJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBalanceJTextFieldActionPerformed(evt);
            }
        });

        viewUserPotentialJButton.setText("View User Habits");
        viewUserPotentialJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserPotentialJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewUserPotentialJButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(accountBalanceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(accountBalanceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(viewUserPotentialJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accountBalanceJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBalanceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountBalanceJTextFieldActionPerformed

    private void viewUserPotentialJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUserPotentialJButtonActionPerformed
        // TODO add your handling code here:
        ViewUserHabitsJPanel viewUserHabitsJPanel = new ViewUserHabitsJPanel(userProcessContainer,organization);
        userProcessContainer.add("ViewUserHabitsJPanel", viewUserHabitsJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewUserPotentialJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountBalanceJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton viewUserPotentialJButton;
    // End of variables declaration//GEN-END:variables
}
