/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.ConsumerRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import UserInterface.SystemAdminRole.ManageNetworksJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author anirudhbedre
 */
public class ConsumerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConsumerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    String consumerName;
    public ConsumerWorkAreaJPanel(JPanel upc, Enterprise enterprise,UserAccount userAccount, Network network) {
        initComponents();
        this.userProcessContainer=upc;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
        this.network=network;
        
      // consumerName=userAccount.getEmployee().getName();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        billboardJButton = new javax.swing.JButton();
        goodreadsJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bestbuyJButton = new javax.swing.JButton();
        espnJButton = new javax.swing.JButton();
        imdbJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Consumer Work Area ");

        billboardJButton.setText("Billboard.com");
        billboardJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billboardJButtonActionPerformed(evt);
            }
        });

        goodreadsJButton.setText("Goodreads.com");
        goodreadsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodreadsJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Welcome !!!");

        bestbuyJButton.setText("Bestbuy.com");
        bestbuyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestbuyJButtonActionPerformed(evt);
            }
        });

        espnJButton.setText("ESPN.com");
        espnJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espnJButtonActionPerformed(evt);
            }
        });

        imdbJButton.setText("IMDB.com");
        imdbJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imdbJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billboardJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bestbuyJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goodreadsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espnJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imdbJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(billboardJButton)
                .addGap(18, 18, 18)
                .addComponent(goodreadsJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bestbuyJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(espnJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imdbJButton)
                .addGap(191, 191, 191))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void billboardJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billboardJButtonActionPerformed
        // TODO add your handling code here:
         BillboardJPanel billboardJPanel = new BillboardJPanel(userProcessContainer, enterprise,userAccount,network);
        userProcessContainer.add("BillboardJPanel",billboardJPanel);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_billboardJButtonActionPerformed

    private void goodreadsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goodreadsJButtonActionPerformed
        // TODO add your handling code here:
          GoodreadsJPanel goodreadsJPanel = new GoodreadsJPanel(userProcessContainer, enterprise,userAccount,network);
        userProcessContainer.add("GoodreadsJPanel",goodreadsJPanel);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_goodreadsJButtonActionPerformed

    private void bestbuyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestbuyJButtonActionPerformed
        // TODO add your handling code here:
        BestbuyJPanel bestbuyJPanel = new BestbuyJPanel(userProcessContainer, enterprise,userAccount,network);
        userProcessContainer.add("BestbuyJPanel",bestbuyJPanel);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_bestbuyJButtonActionPerformed

    private void espnJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espnJButtonActionPerformed
        // TODO add your handling code here:
        ESPNJPanel espnjp = new ESPNJPanel(userProcessContainer, enterprise,userAccount,network);
        userProcessContainer.add("ESPNJPanel",espnjp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_espnJButtonActionPerformed

    private void imdbJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imdbJButtonActionPerformed
        // TODO add your handling code here:
         IMDBJPanel imdbjp = new IMDBJPanel(userProcessContainer, enterprise,userAccount,network);
        userProcessContainer.add("IMDBJPanel",imdbjp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_imdbJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bestbuyJButton;
    private javax.swing.JButton billboardJButton;
    private javax.swing.JButton espnJButton;
    private javax.swing.JButton goodreadsJButton;
    private javax.swing.JButton imdbJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
